# Generated by Django 4.2 on 2023-04-17 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Coach', models.CharField(max_length=50)),
                ('ListOfPLayer', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Location', models.CharField(max_length=50, null=True)),
                ('Dates', models.CharField(max_length=200, null=True)),
                ('NBPool', models.IntegerField(default=0)),
                ('NBTeamPerPool', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Location', models.CharField(max_length=50)),
                ('Score1', models.IntegerField(default=0)),
                ('Score2', models.IntegerField(default=0)),
                ('Pool', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tournoisApp.pool')),
                ('Team1', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Matchs_team1', to='tournoisApp.team')),
                ('Team2', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Matchs_team2', to='tournoisApp.team')),
            ],
        ),
    ]
