# Generated by Django 4.2 on 2023-04-19 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournoisApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pool',
            name='Tournois',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='tournoisApp.tournament'),
            preserve_default=False,
        ),
    ]
