# Generated by Django 4.2 on 2023-04-27 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournoisApp', '0008_alter_match_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='End_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
