# Generated by Django 4.2 on 2023-05-02 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournoisApp', '0009_tournament_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='Lattitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='Longitude',
            field=models.FloatField(null=True),
        ),
    ]
