# Generated by Django 4.2 on 2023-05-01 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournoisApp', '0009_tournament_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='Encaisse1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='Encaisse2',
            field=models.IntegerField(default=0),
        ),
    ]
