# Generated by Django 4.2 on 2023-05-02 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournoisApp', '0010_match_encaisse1_match_encaisse2'),
        ('tournoisApp', '0010_match_lattitude_match_longitude'),
    ]

    operations = [
    ]
