# Generated by Django 4.2 on 2023-05-02 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournoisApp', '0010_alter_match_pool'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='isPool',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
