# Generated by Django 4.2 on 2023-05-03 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournoisApp', '0010_match_encaisse1_match_encaisse2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='Encaisse1',
        ),
        migrations.RemoveField(
            model_name='match',
            name='Encaisse2',
        ),
    ]
