# Generated by Django 4.2 on 2023-05-03 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournoisApp', '0012_match_tournament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='Score1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='Score2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
