# Generated by Django 4.2 on 2023-05-03 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournoisApp', '0012_alter_comment_date'),
        ('tournoisApp', '0014_match_round'),
    ]

    operations = [
    ]
