# Generated by Django 4.2 on 2023-05-03 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournoisApp', '0010_match_lattitude_match_longitude'),
        ('tournoisApp', '0014_match_round'),
    ]

    operations = [
    ]
