# Generated by Django 4.2 on 2023-05-04 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournoisApp', '0015_merge_20230503_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='Pool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tournoisApp.pool'),
        ),
    ]
