# Generated by Django 4.2 on 2023-05-04 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournoisApp', '0015_merge_0012_alter_comment_date_0014_match_round'),
        ('tournoisApp', '0015_merge_20230503_1634'),
    ]

    operations = [
    ]
