# Generated by Django 4.2 on 2023-05-04 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournoisApp', '0015_merge_20230504_1707'),
        ('tournoisApp', '0016_merge_20230504_1008'),
    ]

    operations = [
    ]
