# Generated by Django 4.2 on 2023-05-04 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournoisApp', '0016_alter_match_pool'),
        ('tournoisApp', '0017_merge_20230504_2011'),
    ]

    operations = [
    ]
